version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=jwidgets
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  web:
    image: jwidgets
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
